// src/pages/team/TeamBlogPublicPage.tsx
// 🔥 팀 블로그 공개 페이지 (외부 유입용)

import { useEffect, useState } from "react";
import "@/styles/team-blog-tokens.css";
import { useParams, useNavigate, Link } from "react-router-dom";
import { doc, getDoc, setDoc, collection, query, where, orderBy, limit, getDocs, Timestamp } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { functions } from "@/lib/firebase";
import { httpsCallable } from "firebase/functions";
import { useAuth } from "@/context/AuthProvider";
import { useTeam } from "@/context/TeamContext";
import { Share2, Users, Eye, Calendar, MapPin, Trophy, Star, Settings, UserPlus } from "lucide-react";
import { track, trackTeamBlogLanding } from "@/lib/analytics";
// 🔥 플랫폼 활동 로그 (퍼널 연결)
import { logTeamJoin } from "@/lib/activityLog";
import {
  HERO_COPY,
  TEAM_TAGLINE,
  TEAM_INFO_COPY,
  RECRUITMENT_COPY,
  JOIN_REQUEST_COPY,
  BLOG_CONTENT_COPY,
  SHARE_COPY,
  ERROR_COPY,
} from "@/constants/teamBlogCopy";
// import { Helmet } from "react-helmet-async"; // 필요시 설치

interface BlogSettings {
  enabled: boolean;
  plan: "free" | "pro";
  teamSlug: string;
}

interface BlogPost {
  id: string;
  title: string;
  content: string;
  excerpt: string;
  seoMeta?: {
    title?: string;
    description?: string;
    keywords?: string[];
  };
  publishedAt?: any;
  viewCount: number;
  postType: string;
  isAutoGenerated?: boolean; // 🔥 5-4: 자동 생성 플래그
  createdBy?: string; // "ai" | "ai_auto" | "user"
}

type TabType = "intro" | "activity" | "reviews";

export default function TeamBlogPublicPage() {
  const { teamSlug } = useParams<{ teamSlug: string }>();
  const navigate = useNavigate();
  const { user } = useAuth();
  const { myTeam } = useTeam();
  const [team, setTeam] = useState<any>(null);
  const [blogSettings, setBlogSettings] = useState<BlogSettings | null>(null);
  const [posts, setPosts] = useState<BlogPost[]>([]);
  const [activeTab, setActiveTab] = useState<TabType>("intro");
  const [loading, setLoading] = useState(true);
  const [isOwner, setIsOwner] = useState(false);
  const [generatingNextPost, setGeneratingNextPost] = useState(false);
  const [isMember, setIsMember] = useState(false);
  const [joinRequestStatus, setJoinRequestStatus] = useState<"none" | "pending" | "approved" | "rejected">("none");
  const [showStickyCTA, setShowStickyCTA] = useState(false);
  const [recentActivity, setRecentActivity] = useState<{
    lastSchedule?: { date: string; event: string };
    lastAttendance?: { date: string; count: number };
    status: "active" | "recruiting" | "inactive";
  } | null>(null);

  // 🔥 팀 블로그 페이지 진입 추적
  useEffect(() => {
    if (teamSlug) {
      track("team_blog_view", {
        teamSlug,
        source: "public",
      });
    }
  }, [teamSlug]);

  // 🔥 팀 정보 및 블로그 설정 조회
  useEffect(() => {
    if (!teamSlug) {
      setLoading(false);
      return;
    }

    const fetchTeamBlog = async () => {
      try {
        setLoading(true);

        // 1️⃣ teamSlug로 팀 찾기 (모든 팀을 스캔 - 향후 인덱스 최적화 필요)
        const teamsRef = collection(db, "teams");
        const teamsSnap = await getDocs(teamsRef);
        
        let foundTeamId: string | null = null;
        for (const teamDoc of teamsSnap.docs) {
          const blogSettingsRef = doc(db, `teams/${teamDoc.id}/blog/settings`);
          const blogSettingsSnap = await getDoc(blogSettingsRef);
          
          if (blogSettingsSnap.exists()) {
            const settings = blogSettingsSnap.data() as BlogSettings;
            if (settings.teamSlug === teamSlug) {
              foundTeamId = teamDoc.id;
              setBlogSettings(settings);
              setTeam({ id: teamDoc.id, ...teamDoc.data() });
              break;
            }
          }
        }

        if (!foundTeamId) {
          setLoading(false);
          return; // 팀을 찾을 수 없음
        }

        // 2️⃣ 블로그 포스트 조회
        const postsRef = collection(db, `teams/${foundTeamId}/blog_posts`);
        const postsQuery = query(
          postsRef,
          where("status", "==", "published"),
          orderBy("publishedAt", "desc"),
          limit(10)
        );
        const postsSnap = await getDocs(postsQuery);
        const postsList: BlogPost[] = [];
        postsSnap.forEach((doc) => {
          postsList.push({
            id: doc.id,
            ...doc.data(),
          } as BlogPost);
        });
        setPosts(postsList);

        // 3️⃣ 최근 활동 데이터 조회 (히어로 영역용) - AI 자동 선택 로직
        try {
          const now = new Date();
          const twoWeeksAgo = new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000);
          const threeWeeksAgo = new Date(now.getTime() - 21 * 24 * 60 * 60 * 1000);

          // 🥇 1순위: 최근 일정 조회 (14일 이내)
          const schedulesRef = collection(db, `teams/${foundTeamId}/schedules`);
          const schedulesQuery = query(
            schedulesRef,
            where("date", ">=", twoWeeksAgo.toISOString().split("T")[0]),
            orderBy("date", "desc"),
            limit(1)
          );
          const schedulesSnap = await getDocs(schedulesQuery);
          
          let lastSchedule: { date: string; event: string } | undefined;
          if (!schedulesSnap.empty) {
            const scheduleData = schedulesSnap.docs[0].data();
            const scheduleDate = scheduleData.date;
            const formattedDate = scheduleDate 
              ? new Date(scheduleDate).toLocaleDateString("ko-KR", { month: "long", day: "numeric", weekday: "short" })
              : "";
            lastSchedule = {
              date: formattedDate,
              event: scheduleData.event || scheduleData.title || "활동",
            };
          }

          // 🥇 1순위: 최근 출석 조회 (14일 이내, 3명 이상)
          const attendanceRef = collection(db, `teams/${foundTeamId}/attendance`);
          const attendanceQuery = query(
            attendanceRef,
            where("date", ">=", twoWeeksAgo.toISOString().split("T")[0]),
            orderBy("date", "desc"),
            limit(1)
          );
          const attendanceSnap = await getDocs(attendanceQuery);
          
          let lastAttendance: { date: string; count: number } | undefined;
          if (!attendanceSnap.empty) {
            const attendanceData = attendanceSnap.docs[0].data();
            const participantCount = attendanceData.participants?.length || attendanceData.count || 0;
            
            // 3명 이상 참여한 경우만 표시
            if (participantCount >= 3) {
              const attendanceDate = attendanceData.date;
              const formattedDate = attendanceDate 
                ? new Date(attendanceDate).toLocaleDateString("ko-KR", { month: "long", day: "numeric" })
                : "";
              lastAttendance = {
                date: formattedDate,
                count: participantCount,
              };
            }
          }

          // 🥈 2순위: 최근 블로그 글 (21일 이내, 활동 데이터 없을 때)
          let lastBlogPost: { title: string; date: string } | undefined;
          if (!lastSchedule && !lastAttendance && postsList.length > 0) {
            const recentPost = postsList.find(p => {
              if (!p.publishedAt) return false;
              const postDate = p.publishedAt.toDate ? p.publishedAt.toDate() : new Date(p.publishedAt);
              return postDate >= threeWeeksAgo;
            });
            
            if (recentPost) {
              const postDate = recentPost.publishedAt?.toDate 
                ? recentPost.publishedAt.toDate() 
                : new Date(recentPost.publishedAt || Date.now());
              lastBlogPost = {
                title: recentPost.title,
                date: postDate.toLocaleDateString("ko-KR", { month: "long", day: "numeric" }),
              };
            }
          }

          // 팀 상태 판단 (🟢 활발한 팀 / 🟡 활동 중 / ⚪ 준비 중)
          let status: "active" | "recruiting" | "inactive";
          if (lastSchedule || lastAttendance) {
            status = "active"; // 🟢 활발한 팀
          } else if (lastBlogPost) {
            status = "recruiting"; // 🟡 활동 중
          } else {
            status = "recruiting"; // ⚪ 준비 중 (활동 없어도 모집은 가능)
          }

          setRecentActivity({
            lastSchedule,
            lastAttendance,
            status,
          });
        } catch (error) {
          console.error("최근 활동 조회 실패:", error);
          setRecentActivity({ status: "recruiting" });
        }

        // 4️⃣ 소유자 및 멤버 확인
        if (user?.uid && team) {
          const teamData = team;
          const owners = teamData.owners || [];
          setIsOwner(owners.includes(user.uid));

          // 멤버 확인 (team_members 컬렉션)
          try {
            const teamMembersQuery = query(
              collection(db, "team_members"),
              where("teamId", "==", foundTeamId),
              where("uid", "==", user.uid),
              limit(1)
            );
            const membersSnap = await getDocs(teamMembersQuery);
            setIsMember(!membersSnap.empty);

            // 가입 요청 상태 확인
            if (!membersSnap.empty) {
              setJoinRequestStatus("approved");
            } else {
              const joinRequestRef = doc(db, "team_requests", `${foundTeamId}_${user.uid}`);
              const requestSnap = await getDoc(joinRequestRef);
              if (requestSnap.exists()) {
                const requestData = requestSnap.data();
                setJoinRequestStatus(requestData.status || "pending");
              }
            }
          } catch (error) {
            console.error("멤버/요청 상태 확인 실패:", error);
          }
        }

        // 5️⃣ URL 파라미터로 자동 가입 요청 (로그인 완료 후 복귀)
        const urlParams = new URLSearchParams(window.location.search);
        if (urlParams.get("join") === "true" && user?.uid && !isMember && joinRequestStatus === "none") {
          // 자동으로 가입 요청 생성 (비동기)
          (async () => {
            try {
              const joinRequestRef = doc(db, "team_requests", `${foundTeamId}_${user.uid}`);
              const existingRequest = await getDoc(joinRequestRef);
              
              if (!existingRequest.exists()) {
                await setDoc(joinRequestRef, {
                  teamId: foundTeamId,
                  uid: user.uid,
                  status: "pending",
                  createdAt: new Date(),
                  message: `${team.name} 팀에 가입하고 싶습니다.`,
                });
                setJoinRequestStatus("pending");
                track("team_blog_join_request_sent", {
                  teamId: foundTeamId,
                  teamSlug: blogSettings?.teamSlug,
                  hasMessage: false,
                  source: "auto_after_login",
                });
              }
            } catch (error) {
              console.error("자동 가입 요청 생성 실패:", error);
            }
          })();
        }

        setLoading(false);
      } catch (error) {
        console.error("팀 블로그 조회 실패:", error);
        setLoading(false);
      }
    };

    fetchTeamBlog();
  }, [teamSlug, user?.uid]);

  // 🔥 모바일 Sticky CTA (스크롤 40% 이후 표시)
  useEffect(() => {
    const handleScroll = () => {
      const scrollPercent = (window.scrollY / (document.documentElement.scrollHeight - window.innerHeight)) * 100;
      setShowStickyCTA(scrollPercent >= 40);
    };

    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  // 🔥 조회수 증가 (첫 방문 시)
  useEffect(() => {
    if (team?.id && posts.length > 0) {
      const incrementViewCount = async () => {
        try {
          const latestPost = posts[0];
          if (latestPost.id) {
            const postRef = doc(db, `teams/${team.id}/blog_posts/${latestPost.id}`);
            await getDoc(postRef).then(async (snap) => {
              if (snap.exists()) {
                // 조회수는 서버에서 증가시키는 것이 안전하지만, 여기서는 클라이언트에서 처리
                // (실제로는 Cloud Function에서 처리 권장)
              }
            });
          }
        } catch (error) {
          console.error("조회수 증가 실패:", error);
        }
      };

      // 첫 방문 시에만 조회수 증가 (로컬 스토리지로 중복 방지)
      const viewKey = `blog_view_${team.id}_${posts[0].id}`;
      if (!localStorage.getItem(viewKey)) {
        incrementViewCount();
        localStorage.setItem(viewKey, "true");
      }
    }
  }, [team?.id, posts]);

  // 🔥 SEO 메타 태그 동적 설정 (Hook 규칙 준수: early return 전에 배치)
  useEffect(() => {
    if (!team || !blogSettings) return; // early return은 useEffect 내부에서만
    
    // 🔥 introPost를 useEffect 내부에서 계산 (선언 순서 문제 해결)
    const currentIntroPost = posts.find((p) => p.postType === "intro");
    
    // 🔥 4단계: SEO 최소 세팅 자동 적용
    // <title> 자동 생성: {팀명} | 팀 블로그
    const seoTitle = `${team.name} | 팀 블로그`;
    
    // <meta description>: 팀명 + 지역 + 활동 요약
    let seoDescription = "";
    if (currentIntroPost?.excerpt) {
      seoDescription = `${currentIntroPost.excerpt.substring(0, 120)}...`;
    } else {
      const locationPart = team.location ? `${team.location} ` : "";
      const sportPart = team.sportType === "football" ? "축구" : team.sportType || "스포츠";
      seoDescription = `${team.name} ${locationPart}${sportPart} 팀의 활동 기록을 모아둔 블로그입니다.`;
    }
    
    const seoKeywords = [
      team.name, 
      "팀 블로그", 
      team.sportType === "football" ? "축구" : team.sportType || "스포츠",
      team.location || "",
      "활동 기록"
    ].filter(Boolean);
    
    if (seoTitle) {
      document.title = seoTitle;
    }
    
    // 메타 태그 업데이트
    const updateMetaTag = (name: string, content: string, isProperty = false) => {
      const attribute = isProperty ? "property" : "name";
      let meta = document.querySelector(`meta[${attribute}="${name}"]`);
      if (!meta) {
        meta = document.createElement("meta");
        meta.setAttribute(attribute, name);
        document.head.appendChild(meta);
      }
      meta.setAttribute("content", content);
    };

    updateMetaTag("description", seoDescription);
    if (seoKeywords.length > 0) {
      updateMetaTag("keywords", seoKeywords.join(", "));
    }
    // Open Graph 메타 태그 (공유 카드용)
    updateMetaTag("og:title", seoTitle, true);
    updateMetaTag("og:description", seoDescription, true);
    updateMetaTag("og:url", `${window.location.origin}/teams/${blogSettings.teamSlug}/blog`, true);
    updateMetaTag("og:type", "website", true);
    // OG Image는 향후 카드형 이미지 생성 시 추가
  }, [team, blogSettings, posts]);

  // 🔥 6-2: A/B 공유 메시지 (전환율 2배 목표)
  const [shareMessageVariant, setShareMessageVariant] = useState<"A" | "B" | "C">("A");
  
  // 조회수 기반으로 메시지 선택 (10명 이상이면 B, 30명 이상이면 C)
  useEffect(() => {
    if (posts.length > 0) {
      const totalViews = posts.reduce((sum, post) => sum + (post.viewCount || 0), 0);
      if (totalViews >= 30) {
        setShareMessageVariant("C"); // 행동 유도
      } else if (totalViews >= 10) {
        setShareMessageVariant("B"); // 호기심
      } else {
        setShareMessageVariant("A"); // 신뢰
      }
    }
  }, [posts]);

  // 🔥 공유 기능 (A/B 메시지 적용)
  const handleShare = async () => {
    if (!team || !blogSettings) return;

    const { getShareMessage } = await import("@/constants/blogShareMessages");
    const shareMsg = getShareMessage(shareMessageVariant);
    const blogUrl = `${window.location.origin}/teams/${blogSettings.teamSlug}/blog`;

    const shareData = {
      title: `${shareMsg.emoji} ${shareMsg.title}`,
      text: `${shareMsg.message}\n\n${blogUrl}`,
      url: blogUrl,
    };

    try {
      if (navigator.share) {
        await navigator.share(shareData);
        track("team_blog_share", {
          teamId: team.id,
          teamSlug: blogSettings.teamSlug,
          variant: shareMessageVariant,
          tone: shareMsg.tone,
        });
      } else {
        await navigator.clipboard.writeText(`${shareMsg.message}\n\n${blogUrl}`);
        alert("블로그 링크가 클립보드에 복사되었습니다!");
        track("team_blog_share", {
          teamId: team.id,
          teamSlug: blogSettings.teamSlug,
          method: "clipboard",
          variant: shareMessageVariant,
          tone: shareMsg.tone,
        });
      }
    } catch (error) {
      console.error("공유 실패:", error);
    }
  };

  // 🔥 가입하기
  const handleJoin = async () => {
    if (!team) return;

    track("team_blog_join_click", {
      teamId: team.id,
      teamSlug: blogSettings?.teamSlug,
      source: "hero",
    });

    // 케이스 D: 관리자 (소유자)
    if (isOwner) {
      navigate(`/sports/${team.sportType || "football"}/team/${team.id}`);
      return;
    }

    // 케이스 C: 이미 멤버
    if (isMember) {
      navigate(`/sports/${team.sportType || "football"}/team/${team.id}`);
      return;
    }

    // 케이스 A: 비로그인 사용자
    if (!user) {
      track("team_join_login_required", {
        teamId: team.id,
        teamSlug: blogSettings?.teamSlug,
      });
      // 로그인 페이지로 이동 (리다이렉트 URL 포함)
      navigate(`/start?redirect=${encodeURIComponent(`/teams/${blogSettings?.teamSlug}/blog?join=true`)}`);
      return;
    }

    // 케이스 B: 로그인된 사용자 - 가입 요청 생성
    try {
      const joinRequestRef = doc(db, "team_requests", `${team.id}_${user.uid}`);
      const existingRequest = await getDoc(joinRequestRef);

      if (existingRequest.exists()) {
        const existingData = existingRequest.data();
        if (existingData.status === "pending") {
          track("team_join_request_duplicate", {
            teamId: team.id,
            teamSlug: blogSettings?.teamSlug,
          });
          alert(`${JOIN_REQUEST_COPY.duplicate.title}\n${JOIN_REQUEST_COPY.duplicate.message}`);
          setJoinRequestStatus("pending");
          return;
        }
      }

      await setDoc(joinRequestRef, {
        teamId: team.id,
        uid: user.uid,
        status: "pending",
        createdAt: new Date(),
        message: `${team.name} 팀에 가입하고 싶습니다.`,
      });

      // 🔥 퍼널 연결: 팀 가입 로그
      logTeamJoin(team.id, team.name);

      setJoinRequestStatus("pending");
      alert(`${JOIN_REQUEST_COPY.success.title}\n${JOIN_REQUEST_COPY.success.message}`);
      
      track("team_blog_join_request_sent", {
        teamId: team.id,
        teamSlug: blogSettings?.teamSlug,
        hasMessage: false,
      });
    } catch (error) {
      console.error("가입 요청 생성 실패:", error);
      alert(`${JOIN_REQUEST_COPY.error.title}\n${JOIN_REQUEST_COPY.error.message}`);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <p className="text-gray-600">{ERROR_COPY.loading}</p>
        </div>
      </div>
    );
  }

  if (!team || !blogSettings) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <p className="text-gray-600 mb-4">{ERROR_COPY.notFound.title}</p>
          <Link to="/sports-hub" className="text-blue-600 hover:underline">
            {ERROR_COPY.notFound.action}
          </Link>
        </div>
      </div>
    );
  }

  const introPost = posts.find((p) => p.postType === "intro");
  const activityPosts = posts.filter((p) => p.postType !== "intro");

  return (
    <>

      <div className="min-h-screen bg-gray-50">
        {/* 상단 네비게이션 */}
        <nav className="bg-white border-b border-gray-200">
          <div className="container mx-auto px-4 py-3">
            <div className="flex items-center justify-between">
              <button
                onClick={() => {
                  const sportType = team?.sportType || "football"; // 기본값: football
                  console.log("🔍 [TeamBlogPublicPage] 돌아가기 클릭:", { 
                    team, 
                    sportType, 
                    hasTeam: !!team,
                    teamSportType: team?.sportType 
                  });
                  navigate(`/sports/${sportType}`);
                }}
                className="text-blue-600 hover:text-blue-700"
              >
                ← 운동모임 목록으로 돌아가기
              </button>
              <div className="flex items-center gap-4">
                {isOwner && (
                  <button
                    onClick={() => navigate(`/sports/${team.sportType || "football"}/team/${team.id}`)}
                    className="px-4 py-2 text-sm bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors"
                  >
                    팀 대시보드로 이동
                  </button>
                )}
              </div>
            </div>
          </div>
        </nav>

        <div className="container mx-auto px-4 py-8 max-w-6xl">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* 메인 콘텐츠 */}
            <div className="lg:col-span-2">
              {/* 🔥 ① 히어로 영역 (Above the Fold) - 웹: 7cols + 5cols 구조 */}
              <div className="bg-white rounded-2xl shadow-lg p-6 lg:p-8 mb-6 border-2 border-blue-100 min-h-[72vh] lg:min-h-[60vh]">
                {/* 모바일: 단일 컬럼 */}
                <div className="lg:hidden space-y-4">
                  {/* 상태 배지 (기록 중심) */}
                  {recentActivity?.status === "active" && (
                    <div className="px-3 py-1 bg-green-100 text-green-700 text-xs font-medium rounded-full inline-block">
                      🟢 최근 활동 기록 중
                    </div>
                  )}
                  {recentActivity?.status === "recruiting" && (
                    <div className="px-3 py-1 bg-gray-100 text-gray-700 text-xs font-medium rounded-full inline-block">
                      기록 준비 중
                    </div>
                  )}

                  {/* 팀명 (H1) */}
                  <h1 className="text-3xl font-bold text-gray-900">{team.name}</h1>

                  {/* 🔥 고정 카피: 외부인 5초 이해 */}
                  <p className="text-base font-medium text-gray-800 bg-blue-50 px-4 py-2 rounded-lg border border-blue-200">
                    이 팀은 이렇게 활동합니다.
                  </p>

                  {/* 한 줄 설명 (기록 강조) */}
                  <p className="text-base text-gray-600">
                    이 팀의 활동 기록을 모아둔 페이지입니다.
                  </p>

                  {/* 최근 활동 요약 */}
                  <div className="space-y-2 text-sm text-gray-600">
                    {recentActivity?.lastSchedule && (
                      <div className="flex items-center gap-2">
                        <Calendar size={16} className="text-blue-600" />
                        <span>
                          <strong>🟢 최근 경기 완료</strong> · {recentActivity.lastSchedule.date}
                        </span>
                      </div>
                    )}
                    {recentActivity?.lastAttendance && !recentActivity?.lastSchedule && (
                      <div className="flex items-center gap-2">
                        <Users size={16} className="text-blue-600" />
                        <span>
                          <strong>🟢 이번 주 훈련 완료</strong> ({recentActivity.lastAttendance.count}명 참여)
                        </span>
                      </div>
                    )}
                    {!recentActivity?.lastSchedule && !recentActivity?.lastAttendance && (
                      <div className="text-gray-500">
                        최근 활동 정보를 준비 중입니다.
                      </div>
                    )}
                  </div>

                  {/* 신뢰 배지 */}
                  <div className="flex flex-wrap gap-2">
                    <span className="px-3 py-1 bg-blue-50 text-blue-700 rounded-full text-xs font-medium border border-blue-200">
                      ✔ 주 1회 활동
                    </span>
                    <span className="px-3 py-1 bg-blue-50 text-blue-700 rounded-full text-xs font-medium border border-blue-200">
                      ✔ 실제 팀 운영 중
                    </span>
                    {blogSettings.plan === "pro" && (
                      <span className="px-3 py-1 bg-purple-50 text-purple-700 rounded-full text-xs font-medium border border-purple-200">
                        ✔ AI 관리 블로그
                      </span>
                    )}
                  </div>

                  {/* CTA 버튼 */}
                  <div className="flex flex-col sm:flex-row gap-3 pt-4">
                    {isOwner ? (
                      <button
                        onClick={() => navigate(`/sports/${team.sportType || "football"}/team/${team.id}`)}
                        className="flex-1 px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center justify-center gap-2 font-bold shadow-md"
                      >
                        <Settings size={18} />
                        팀 관리하기
                      </button>
                    ) : isMember ? (
                      <button
                        onClick={() => navigate(`/sports/${team.sportType || "football"}/team/${team.id}`)}
                        className="flex-1 px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center justify-center gap-2 font-bold shadow-md"
                      >
                        일정 보기
                      </button>
                    ) : joinRequestStatus === "pending" ? (
                      <button
                        className="flex-1 px-6 py-3 bg-gray-400 text-white rounded-lg cursor-not-allowed flex items-center justify-center gap-2 font-bold"
                        disabled
                      >
                        가입 승인 대기중
                      </button>
                    ) : (
                      <>
                        <button
                          onClick={handleJoin}
                          className="flex-1 px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center justify-center gap-2 font-bold shadow-md"
                        >
                          <UserPlus size={18} />
                          함께 운동하기
                        </button>
                        <button
                          onClick={() => setActiveTab("intro")}
                          className="px-4 py-3 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors flex items-center gap-2 font-medium"
                        >
                          팀 소개 보기
                        </button>
                      </>
                    )}
                  </div>
                </div>

                {/* 웹: 7cols + 5cols 그리드 */}
                <div className="hidden lg:grid lg:grid-cols-12 lg:gap-8 lg:items-start">
                  {/* 좌측 7cols */}
                  <div className="lg:col-span-7 space-y-4">
                    {/* 상태 배지 (기록 중심) */}
                    {recentActivity?.status === "active" && (
                      <div className="px-3 py-1 bg-green-100 text-green-700 text-xs font-medium rounded-full inline-block">
                        🟢 최근 활동 기록 중
                      </div>
                    )}
                    {recentActivity?.status === "recruiting" && (
                      <div className="px-3 py-1 bg-gray-100 text-gray-700 text-xs font-medium rounded-full inline-block">
                        기록 준비 중
                      </div>
                    )}

                    {/* 팀명 (H1) */}
                    <h1 className="text-4xl font-bold text-gray-900">{team.name}</h1>

                    {/* 🔥 고정 카피: 외부인 5초 이해 */}
                    <p className="text-lg font-medium text-gray-800 bg-blue-50 px-4 py-2 rounded-lg border border-blue-200">
                      이 팀은 이렇게 활동합니다.
                    </p>

                    {/* 한 줄 설명 (기록 강조) */}
                    <p className="text-lg text-gray-600">
                      이 팀의 활동 기록을 모아둔 페이지입니다.
                    </p>

                    {/* 최근 활동 요약 */}
                    <div className="space-y-2 text-base text-gray-600">
                      {recentActivity?.lastSchedule && (
                        <div className="flex items-center gap-2">
                          <Calendar size={20} className="text-blue-600" />
                          <span>
                            <strong>🟢 최근 경기 완료</strong> · {recentActivity.lastSchedule.date}
                          </span>
                        </div>
                      )}
                      {recentActivity?.lastAttendance && !recentActivity?.lastSchedule && (
                        <div className="flex items-center gap-2">
                          <Users size={20} className="text-blue-600" />
                          <span>
                            <strong>🟢 이번 주 훈련 완료</strong> ({recentActivity.lastAttendance.count}명 참여)
                          </span>
                        </div>
                      )}
                      {!recentActivity?.lastSchedule && !recentActivity?.lastAttendance && (
                        <div className="text-gray-500">
                          최근 활동 정보를 준비 중입니다.
                        </div>
                      )}
                    </div>

                    {/* 신뢰 배지 */}
                    <div className="flex flex-wrap gap-2">
                      <span className="px-3 py-1 bg-blue-50 text-blue-700 rounded-full text-xs font-medium border border-blue-200">
                        ✔ 주 1회 활동
                      </span>
                      <span className="px-3 py-1 bg-blue-50 text-blue-700 rounded-full text-xs font-medium border border-blue-200">
                        ✔ 실제 팀 운영 중
                      </span>
                      {blogSettings.plan === "pro" && (
                        <span className="px-3 py-1 bg-purple-50 text-purple-700 rounded-full text-xs font-medium border border-purple-200">
                          ✔ AI 관리 블로그
                        </span>
                      )}
                    </div>

                    {/* CTA 버튼 */}
                    <div className="flex gap-3 pt-4">
                      {isOwner ? (
                        <button
                          onClick={() => navigate(`/sports/${team.sportType || "football"}/team/${team.id}`)}
                          className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2 font-bold shadow-md"
                        >
                          <Settings size={18} />
                          팀 관리하기
                        </button>
                      ) : isMember ? (
                        <button
                          onClick={() => navigate(`/sports/${team.sportType || "football"}/team/${team.id}`)}
                          className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2 font-bold shadow-md"
                        >
                          일정 보기
                        </button>
                      ) : joinRequestStatus === "pending" ? (
                        <button
                          className="px-6 py-3 bg-gray-400 text-white rounded-lg cursor-not-allowed flex items-center gap-2 font-bold"
                          disabled
                        >
                          가입 승인 대기중
                        </button>
                      ) : (
                        <>
                          <button
                            onClick={handleJoin}
                            className="px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2 font-bold shadow-md"
                          >
                            <UserPlus size={18} />
                            함께 운동하기
                          </button>
                          <button
                            onClick={() => setActiveTab("intro")}
                            className="px-4 py-3 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 transition-colors flex items-center gap-2 font-medium"
                          >
                            팀 소개 보기
                          </button>
                        </>
                      )}
                    </div>
                  </div>

                  {/* 우측 5cols - HeroActivityCard (이미지/활동 요약) */}
                  <div className="lg:col-span-5">
                    <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-xl p-6 border border-blue-200">
                      {/* 최근 활동 카드 내용 */}
                      {recentActivity?.lastSchedule && (
                        <div className="text-center">
                          <div className="text-4xl mb-2">⚽</div>
                          <p className="text-sm text-gray-600 mb-2">최근 경기</p>
                          <p className="text-lg font-semibold text-gray-900">{recentActivity.lastSchedule.event}</p>
                          <p className="text-xs text-gray-500 mt-1">{recentActivity.lastSchedule.date}</p>
                        </div>
                      )}
                      {recentActivity?.lastAttendance && !recentActivity?.lastSchedule && (
                        <div className="text-center">
                          <div className="text-4xl mb-2">👥</div>
                          <p className="text-sm text-gray-600 mb-2">이번 주 훈련</p>
                          <p className="text-lg font-semibold text-gray-900">{recentActivity.lastAttendance.count}명 참여</p>
                          <p className="text-xs text-gray-500 mt-1">{recentActivity.lastAttendance.date}</p>
                        </div>
                      )}
                      {!recentActivity?.lastSchedule && !recentActivity?.lastAttendance && (
                        <div className="text-center">
                          <div className="text-4xl mb-2">⚽</div>
                          <p className="text-sm text-gray-600">활동 정보 준비 중</p>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </div>

              {/* ② 팀 메타 정보 (압축 신뢰, DB 없으면 비노출) */}
              <div className="bg-white rounded-2xl shadow-sm p-6 mb-6">
                <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
                  {team.location && (
                    <div className="flex items-center gap-2">
                      <MapPin size={20} className="text-gray-400" />
                      <div>
                        <p className="text-xs text-gray-500">활동 지역</p>
                        <p className="font-semibold text-gray-900">{team.location}</p>
                      </div>
                    </div>
                  )}
                  {team.ageGroup && (
                    <div className="flex items-center gap-2">
                      <Users size={20} className="text-gray-400" />
                      <div>
                        <p className="text-xs text-gray-500">연령대</p>
                        <p className="font-semibold text-gray-900">{team.ageGroup}</p>
                      </div>
                    </div>
                  )}
                  {team.sportType && (
                    <div className="flex items-center gap-2">
                      <Trophy size={20} className="text-gray-400" />
                      <div>
                        <p className="text-xs text-gray-500">종목</p>
                        <p className="font-semibold text-gray-900">{team.sportType === "football" ? "축구" : team.sportType}</p>
                      </div>
                    </div>
                  )}
                  <div className="flex items-center gap-2">
                    <Calendar size={20} className="text-gray-400" />
                    <div>
                      <p className="text-xs text-gray-500">활동 빈도</p>
                      <p className="font-semibold text-gray-900">주 1회</p>
                    </div>
                  </div>
                </div>
              </div>

              {/* 관리자 전용: 새 기록 생성 버튼 */}
              {isOwner && (
                <div className="bg-white rounded-2xl shadow-sm p-6 mb-6 border border-gray-200">
                  <div className="flex items-center justify-between">
                    <div>
                      <h3 className="text-lg font-semibold text-gray-900 mb-1">기록 관리</h3>
                      <p className="text-sm text-gray-600">새로운 활동 기록을 추가할 수 있습니다</p>
                    </div>
                    <button
                      onClick={() => navigate(`/sports/${team.sportType || "football"}/team/${team.id}`)}
                      className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm font-medium"
                    >
                      새 기록 생성
                    </button>
                  </div>
                </div>
              )}

              {/* ④ 콘텐츠 영역 (AI 블로그 미리보기) - 항상 표시, 빈 상태 제거 */}
              <div className="bg-white rounded-2xl shadow-sm p-6 mb-6">
                <h3 className="text-xl font-semibold text-gray-900 mb-4">📝 최근 소식</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-4">
                  {posts.length > 0 ? (
                    posts.slice(0, 3).map((post) => (
                      <article key={post.id} className="border border-gray-200 rounded-lg p-4 hover:shadow-md transition-shadow">
                        <h4 className="text-lg font-semibold text-gray-900 mb-2 line-clamp-2">{post.title}</h4>
                        <p className="text-sm text-gray-600 mb-3 line-clamp-2">{post.excerpt || "요약이 없습니다."}</p>
                        <div className="flex items-center justify-between text-xs text-gray-400">
                          <span>
                            {post.publishedAt
                              ? new Date(post.publishedAt.toDate ? post.publishedAt.toDate() : post.publishedAt).toLocaleDateString("ko-KR")
                              : "날짜 없음"}
                          </span>
                          {post.isAutoGenerated && (
                            <span className="px-2 py-1 bg-blue-50 text-blue-700 rounded-full">자동</span>
                          )}
                        </div>
                        {/* 🔥 관리자만 보이는 조회수 */}
                        {isOwner && (
                          <div className="mt-2 pt-2 border-t border-gray-100 text-xs text-gray-500">
                            👁️ {post.viewCount || 0}명이 읽었습니다
                          </div>
                        )}
                      </article>
                    ))
                  ) : (
                    // 🔥 빈 상태 완전 제거: 최소 1개 카드로 대체
                    <article className="border border-dashed border-gray-300 rounded-lg p-8 text-center bg-gray-50">
                      <div className="text-3xl mb-2">📝</div>
                      <p className="text-sm text-gray-500">첫 글이 곧 여기에 표시됩니다</p>
                    </article>
                  )}
                </div>
                {posts.length > 0 && (
                  <div className="text-center">
                    <button
                      onClick={() => setActiveTab("intro")}
                      className="text-blue-600 hover:text-blue-700 font-medium"
                    >
                      블로그 전체 보기 →
                    </button>
                  </div>
                )}
              </div>

              {/* 탭 네비게이션 (전체 보기용) */}
              <div className="bg-white rounded-2xl shadow-sm mb-6">
                <div className="border-b border-gray-200">
                  <div className="flex">
                    <button
                      onClick={() => setActiveTab("intro")}
                      className={`px-6 py-4 font-medium transition-colors ${
                        activeTab === "intro"
                          ? "text-blue-600 border-b-2 border-blue-600"
                          : "text-gray-600 hover:text-gray-900"
                      }`}
                    >
                      {BLOG_CONTENT_COPY.tabs.intro}
                    </button>
                    <button
                      onClick={() => setActiveTab("activity")}
                      className={`px-6 py-4 font-medium transition-colors ${
                        activeTab === "activity"
                          ? "text-blue-600 border-b-2 border-blue-600"
                          : "text-gray-600 hover:text-gray-900"
                      }`}
                    >
                      {BLOG_CONTENT_COPY.tabs.activity}
                    </button>
                    <button
                      onClick={() => setActiveTab("reviews")}
                      className={`px-6 py-4 font-medium transition-colors ${
                        activeTab === "reviews"
                          ? "text-blue-600 border-b-2 border-blue-600"
                          : "text-gray-600 hover:text-gray-900"
                      }`}
                    >
                      {BLOG_CONTENT_COPY.tabs.reviews}
                    </button>
                  </div>
                </div>

                {/* 탭 콘텐츠 */}
                <div className="p-6">
                  {activeTab === "intro" && (
                    <div>
                      {introPost ? (
                        <>
                          <div
                            className="prose max-w-none"
                            dangerouslySetInnerHTML={{ __html: introPost.content }}
                          />
                          {/* 🔥 2단계 + 5-4: AI 신뢰도 강화: 글 하단 고정 문구 + 생성 시점 */}
                          <div className="mt-8 pt-6 border-t border-gray-200">
                            <div className="text-center space-y-2">
                              {introPost.isAutoGenerated || introPost.createdBy === "ai_auto" ? (
                                <>
                                  <p className="text-sm text-gray-500">
                                    🤖 이 글은 AI가 자동으로 생성한 팀 콘텐츠입니다
                                  </p>
                                  {introPost.publishedAt && (
                                    <p className="text-xs text-gray-400">
                                      자동 생성됨 · {new Date(introPost.publishedAt.toDate ? introPost.publishedAt.toDate() : introPost.publishedAt).toLocaleDateString("ko-KR", {
                                        year: "numeric",
                                        month: "long",
                                        day: "numeric"
                                      })}
                                    </p>
                                  )}
                                </>
                              ) : (
                                <>
                                  <p className="text-sm text-gray-500">
                                    이 글은 팀 활동 데이터를 바탕으로 AI가 작성했습니다.
                                  </p>
                                  {introPost.publishedAt && (
                                    <p className="text-xs text-gray-400">
                                      생성일: {new Date(introPost.publishedAt.toDate ? introPost.publishedAt.toDate() : introPost.publishedAt).toLocaleDateString("ko-KR", {
                                        year: "numeric",
                                        month: "long",
                                        day: "numeric"
                                      })}
                                    </p>
                                  )}
                                </>
                              )}
                            </div>
                            {/* 🔥 3단계: 관리자 전용 성장 트리거 (은근하게) */}
                            {isOwner && (
                              <div className="mt-6 pt-6 border-t border-gray-200 bg-blue-50 rounded-lg p-4">
                                <div className="mb-3">
                                  <p className="text-sm font-medium text-gray-900">
                                    👁️ 이 글은 {introPost.viewCount || 0}명이 읽었습니다
                                  </p>
                                </div>
                                <button
                                  onClick={async () => {
                                    if (generatingNextPost) return;
                                    
                                    try {
                                      setGeneratingNextPost(true);
                                      track("team_blog_next_post_click", { teamId: team.id });
                                      
                                      // 🔥 다음 글 생성 (서버에서 자동으로 주제 결정)
                                      const generateBlogPost = httpsCallable(functions, "generateTeamBlogPost");
                                      const result = await generateBlogPost({
                                        teamId: team.id,
                                        // postType 미지정 → 서버에서 자동 결정
                                      });
                                      
                                      if (result.data) {
                                        const data = result.data as any;
                                        track("team_blog_next_post_success", { teamId: team.id, postId: data.postId, postType: data.postType });
                                        
                                        // 성공 토스트
                                        const toast = document.createElement("div");
                                        toast.className = "fixed top-4 right-4 bg-green-600 text-white px-6 py-3 rounded-lg shadow-lg z-50 flex items-center gap-2";
                                        toast.innerHTML = `
                                          <span class="text-xl">✨</span>
                                          <span>다음 글이 생성되었습니다!</span>
                                        `;
                                        document.body.appendChild(toast);
                                        setTimeout(() => {
                                          toast.style.opacity = "0";
                                          toast.style.transition = "opacity 0.3s";
                                          setTimeout(() => toast.remove(), 300);
                                        }, 3000);
                                        
                                        // 페이지 새로고침하여 새 글 표시
                                        window.location.reload();
                                      }
                                    } catch (error: any) {
                                      console.error("다음 글 생성 실패:", error);
                                      alert(`다음 글 생성에 실패했습니다: ${error?.message || "알 수 없는 오류"}`);
                                      track("team_blog_next_post_failed", { teamId: team.id, error: error?.message });
                                    } finally {
                                      setGeneratingNextPost(false);
                                    }
                                  }}
                                  disabled={generatingNextPost}
                                  className="w-full px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm font-medium mb-2 disabled:opacity-50 disabled:cursor-not-allowed"
                                >
                                  {generatingNextPost ? "생성 중..." : "다음 글 자동 생성하기"}
                                </button>
                                {/* 🔥 6-2: Pro 전환 트리거 강화 (자연스러운 결제) */}
                                {blogSettings?.plan === "free" && (introPost.viewCount || 0) >= 10 && (
                                  <div className="mt-4 pt-4 border-t border-gray-100 bg-gradient-to-r from-blue-50 to-purple-50 rounded-lg p-4">
                                    <p className="text-sm font-medium text-gray-900 mb-2">
                                      💡 관리 시간 절약
                                    </p>
                                    <p className="text-xs text-gray-600 mb-3">
                                      Pro 플랜으로 업그레이드하면 주간 자동 생성, 월간 리포트, SEO 강화를 받을 수 있습니다.
                                    </p>
                                    <button
                                      onClick={() => {
                                        track("team_blog_pro_cta_click", { 
                                          teamId: team.id, 
                                          source: "next_post_button", 
                                          viewCount: introPost.viewCount 
                                        });
                                        // 🔥 6-3: 새 탭 결제
                                        window.open(`/pricing/team-blog?trigger=next_post&teamId=${team.id}`, "_blank");
                                      }}
                                      className="w-full px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-sm font-medium"
                                    >
                                      Pro로 업그레이드 (월 19,000원)
                                    </button>
                                  </div>
                                )}
                              </div>
                            )}
                          </div>
                        </>
                      ) : (
                        // 🔥 빈 상태 완전 제거: 최소한의 안내만
                        <div className="text-center py-8">
                          <p className="text-sm text-gray-500">팀 소개 글을 준비 중입니다</p>
                        </div>
                      )}
                    </div>
                  )}

                  {activeTab === "activity" && (
                    <div className="space-y-6">
                      {activityPosts.length > 0 ? (
                        activityPosts.map((post) => (
                          <article key={post.id} className="border-b border-gray-200 pb-6 last:border-0">
                            <h3 className="text-xl font-semibold text-gray-900 mb-2">{post.title}</h3>
                            <p className="text-gray-600 mb-4">{post.excerpt}</p>
                            <div
                              className="prose max-w-none text-sm"
                              dangerouslySetInnerHTML={{ __html: post.content }}
                            />
                            {/* 🔥 2단계 + 5-4: 공개 블로그 신뢰 장치 - 모든 게시글 하단 고정 문구 */}
                            <div className="mt-6 pt-4 border-t border-gray-200">
                              <div className="text-center space-y-1">
                                {post.isAutoGenerated || post.createdBy === "ai_auto" ? (
                                  <>
                                    <p className="text-xs text-gray-500">
                                      🤖 이 글은 AI가 자동으로 생성한 팀 콘텐츠입니다
                                    </p>
                                    {post.publishedAt && (
                                      <p className="text-xs text-gray-400">
                                        자동 생성됨 · {new Date(post.publishedAt.toDate ? post.publishedAt.toDate() : post.publishedAt).toLocaleDateString("ko-KR", {
                                          year: "numeric",
                                          month: "long",
                                          day: "numeric"
                                        })}
                                      </p>
                                    )}
                                  </>
                                ) : (
                                  <>
                                    <p className="text-xs text-gray-500">
                                      이 글은 팀 활동 데이터를 바탕으로 AI가 작성했습니다
                                    </p>
                                    {post.publishedAt && (
                                      <p className="text-xs text-gray-400">
                                        {new Date(post.publishedAt.toDate ? post.publishedAt.toDate() : post.publishedAt).toLocaleDateString("ko-KR", {
                                          year: "numeric",
                                          month: "long",
                                          day: "numeric"
                                        })}
                                      </p>
                                    )}
                                  </>
                                )}
                              </div>
                            </div>
                            
                            {/* 🔥 3단계: 관리자 전용 성장 트리거 (은근하게) */}
                            {isOwner && (post.viewCount || 0) >= 0 && (
                              <div className="mt-4 pt-4 border-t border-gray-100 bg-gray-50 rounded-lg p-3">
                                <p className="text-xs text-gray-600 mb-2">
                                  👁️ 이 글은 {post.viewCount || 0}명이 읽었습니다
                                </p>
                                {(post.viewCount || 0) >= 10 && blogSettings?.plan === "free" && (
                                  <button
                                    onClick={() => {
                                      track("team_blog_pro_cta_click", { teamId: team.id, source: "activity_view", viewCount: post.viewCount });
                                      navigate(`/pricing/team-blog?trigger=activity_view`);
                                    }}
                                    className="w-full px-3 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors text-xs font-medium"
                                  >
                                    Pro로 업그레이드 → 주간 자동 생성
                                  </button>
                                )}
                              </div>
                            )}
                          </article>
                        ))
                      ) : (
                        // 🔥 빈 상태 완전 제거: 최소한의 안내만
                        <div className="text-center py-8">
                          <p className="text-sm text-gray-500">활동 기록을 준비 중입니다</p>
                        </div>
                      )}
                    </div>
                  )}

                  {activeTab === "reviews" && (
                    <div className="text-center py-12 text-gray-500">
                      <p>{BLOG_CONTENT_COPY.empty.reviews}</p>
                    </div>
                  )}
                </div>
              </div>

            </div>

            {/* 사이드바 */}
            <div className="space-y-6">
              {/* 팀/운영자 정보 */}
              <div className="bg-white rounded-2xl shadow-sm p-6">
                <h2 className="text-lg font-semibold text-gray-900 mb-4">팀/운영자</h2>
                {team.owners && team.owners.length > 0 && (
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-12 h-12 bg-orange-100 rounded-full flex items-center justify-center text-orange-600 font-semibold">
                      {team.owners[0]?.charAt(0) || "운"}
                    </div>
                    <div>
                      <p className="font-medium text-gray-900">팀 운영자</p>
                      <p className="text-sm text-gray-500">평점 ★0.00</p>
                    </div>
                  </div>
                )}
                <p className="text-sm text-gray-500">리뷰 수 0개</p>
              </div>

              {/* 팀 정보 */}
              <div className="bg-white rounded-2xl shadow-sm p-6">
                <h2 className="text-lg font-semibold text-gray-900 mb-4">팀 정보</h2>
                <div className="space-y-3 text-sm">
                  <div className="flex items-center gap-2">
                    <Trophy size={16} className="text-gray-400" />
                    <span className="text-gray-600">종목:</span>
                    <span className="text-gray-900 font-medium">{team.sportType || "미정"}</span>
                  </div>
                  {team.location && (
                    <div className="flex items-center gap-2">
                      <MapPin size={16} className="text-gray-400" />
                      <span className="text-gray-600">활동 지역:</span>
                      <span className="text-gray-900 font-medium">{team.location}</span>
                    </div>
                  )}
                  <div className="flex items-center gap-2">
                    <Users size={16} className="text-gray-400" />
                    <span className="text-gray-600">모집 인원:</span>
                    <span className="text-gray-900 font-medium">
                      {team.memberCount || 0}/{team.maxMembers || 10}명
                    </span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Star size={16} className="text-gray-400" />
                    <span className="text-gray-600">난이도:</span>
                    <span className="text-gray-900 font-medium">{team.difficulty || "초급"}</span>
                  </div>
                </div>
              </div>

              {/* 활동 통계 */}
              <div className="bg-white rounded-2xl shadow-sm p-6">
                <h2 className="text-lg font-semibold text-gray-900 mb-4">활동 통계</h2>
                <div className="space-y-2 text-sm">
                  <button className="w-full text-left px-3 py-2 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors">
                    활성 통계
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* 모바일 Sticky CTA (스크롤 40% 이후) */}
      <div
        className={`lg:hidden fixed bottom-0 left-0 right-0 bg-white border-t border-gray-200 shadow-lg p-4 z-50 transition-transform duration-300 ${
          showStickyCTA ? "translate-y-0" : "translate-y-full"
        }`}
      >
        <div className="container mx-auto">
          {isOwner ? (
            <button
              onClick={() => navigate(`/sports/${team.sportType || "football"}/team/${team.id}`)}
              className="w-full px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center justify-center gap-2 font-bold shadow-md"
            >
              <Settings size={18} />
              팀 관리하기
            </button>
          ) : isMember ? (
            <button
              onClick={() => navigate(`/sports/${team.sportType || "football"}/team/${team.id}`)}
              className="w-full px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center justify-center gap-2 font-bold shadow-md"
            >
              일정 보기
            </button>
          ) : joinRequestStatus === "pending" ? (
            <button
              className="w-full px-6 py-3 bg-gray-400 text-white rounded-lg cursor-not-allowed flex items-center justify-center gap-2 font-bold"
              disabled
            >
              가입 승인 대기중
            </button>
          ) : (
            <button
              onClick={handleJoin}
              className="w-full px-6 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center justify-center gap-2 font-bold shadow-md"
            >
              <UserPlus size={18} />
              함께 운동하기
            </button>
          )}
        </div>
      </div>
    </>
  );
}

