import OpenAI from "openai";
import { aggregateLogs } from "@/utils/aggregateLogs";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import { db } from "@/lib/firebase";
import { addDoc, collection, serverTimestamp } from "firebase/firestore";

const client = new OpenAI({ apiKey: import.meta.env.VITE_OPENAI_API_KEY });

export const POST = async () => {
    try {
        console.log("📊 주간 리포트 생성 시작...");

        // Slack URL 먼저 선언 (나중에 사용됨)
        const slackUrl = import.meta.env.VITE_SLACK_WEBHOOK_URL;

        const logs = await aggregateLogs();
        console.log("📈 집계된 로그 데이터:", {
            total: logs.total,
            geoSample: logs.geoSample?.length || 0,
            devices: Object.keys(logs.devices || {}).length,
            actions: Object.keys(logs.actions || {}).length
        });

        const prompt = `
너는 데이터 분석가야. 다음 로그 데이터를 바탕으로
주간 활동 리포트를 작성해.
형식은 반드시 JSON만 반환해.

{
  "summary": "주간 활동 요약 (한 줄)",
  "insights": [
    "주요 발견사항 1",
    "주요 발견사항 2", 
    "주요 발견사항 3"
  ],
  "recommendations": [
    "개선 추천 1",
    "개선 추천 2",
    "개선 추천 3"
  ],
  "metrics": {
    "totalLogs": ${logs.total || 0},
    "geoCount": ${logs.geoSample?.length || 0},
    "deviceTypes": ${Object.keys(logs.devices || {}).length},
    "actionTypes": ${Object.keys(logs.actions || {}).length}
  }
}

로그 데이터:
- 총 로그 수: ${logs.total || 0}건
- 위치 샘플: ${logs.geoSample?.length || 0}개
- 디바이스 종류: ${Object.keys(logs.devices || {}).length}개
- 액션 종류: ${Object.keys(logs.actions || {}).length}개

상세 데이터: ${JSON.stringify(logs).slice(0, 6000)}

분석 포인트:
1. 사용 패턴과 트렌드
2. 주요 활동 유형
3. 개선 가능한 영역
4. 사용자 행동 인사이트
5. 주간 성과 지표
`;

        const response = await client.chat.completions.create({
            model: "gpt-4o-mini",
            messages: [{ role: "user", content: prompt }],
            response_format: { type: "json_object" },
            temperature: 0.7,
            max_tokens: 1500
        });

        const report = JSON.parse(response.choices[0].message?.content || "{}");
        console.log("✅ AI 리포트 생성 완료:", report);

        // PDF 생성
        const pdf = await PDFDocument.create();
        const page = pdf.addPage([595.28, 841.89]);
        const { width, height } = page.getSize();
        const font = await pdf.embedFont(StandardFonts.Helvetica);
        const boldFont = await pdf.embedFont(StandardFonts.HelveticaBold);

        let y = height - 60;
        const drawText = (text: string, size = 14, gap = 20, isBold = false) => {
            page.drawText(text, {
                x: 50,
                y,
                size,
                font: isBold ? boldFont : font,
                color: rgb(0.2, 0.2, 0.2)
            });
            y -= gap;
        };

        // 헤더
        drawText("📊 YAGO SPORTS - 주간 AI 리포트", 20, 30, true);
        drawText(`작성일: ${new Date().toLocaleString("ko-KR")}`, 12, 20);
        drawText("─".repeat(50), 12, 20);

        // 요약
        drawText("📋 주간 활동 요약", 16, 25, true);
        drawText(report.summary || "데이터 분석 중...", 12, 20);

        // 지표
        drawText("📈 주요 지표", 16, 25, true);
        if (report.metrics) {
            drawText(`• 총 로그 수: ${report.metrics.totalLogs || 0}건`, 12, 18);
            drawText(`• 위치 샘플: ${report.metrics.geoCount || 0}개`, 12, 18);
            drawText(`• 디바이스 유형: ${report.metrics.deviceTypes || 0}개`, 12, 18);
            drawText(`• 액션 유형: ${report.metrics.actionTypes || 0}개`, 12, 18);
        }

        // 인사이트
        drawText("🔍 주요 인사이트", 16, 25, true);
        if (report.insights && Array.isArray(report.insights)) {
            report.insights.forEach((insight: string) => {
                drawText(`• ${insight}`, 12, 18);
            });
        } else {
            drawText("• 데이터 분석 중...", 12, 18);
        }

        // 추천사항
        drawText("🎯 개선 추천", 16, 25, true);
        if (report.recommendations && Array.isArray(report.recommendations)) {
            report.recommendations.forEach((rec: string) => {
                drawText(`• ${rec}`, 12, 18);
            });
        } else {
            drawText("• 분석 중...", 12, 18);
        }

        // 푸터
        y = 50;
        drawText("─".repeat(50), 12, 20);
        drawText("Generated by YAGO SPORTS AI System", 10, 15);
        drawText(`Report ID: ${Date.now()}`, 10, 15);

        const pdfBytes = await pdf.save();
        console.log("📄 PDF 생성 완료:", pdfBytes.length, "bytes");

        // Firestore에 리포트 메타데이터 저장
        try {
            const reportDate = new Date().toISOString();
            const reportData = {
                date: reportDate,
                summary: report.summary || "주간 활동 요약",
                insights: report.insights || [],
                recommendations: report.recommendations || [],
                metrics: report.metrics || {},
                pdfUrl: `https://your-app-domain/api/generateWeeklyReport?date=${reportDate}`,
                createdAt: serverTimestamp(),
                totalLogs: logs.total || 0,
                geoCount: logs.geoSample?.length || 0,
                deviceTypes: Object.keys(logs.devices || {}).length,
                actionTypes: Object.keys(logs.actions || {}).length,
                slackSent: !!slackUrl,
                status: "completed"
            };

            await addDoc(collection(db, "weekly_reports"), reportData);
            console.log("✅ Firestore 저장 완료:", reportData);
        } catch (firestoreError) {
            console.warn("⚠️ Firestore 저장 실패:", firestoreError);
        }

        // Slack 전송 (선택사항)
        if (slackUrl) {
            try {
                await fetch(slackUrl, {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({
                        text: `📈 *YAGO SPORTS 주간 리포트 생성 완료*\n📅 ${new Date().toLocaleDateString("ko-KR")}\n📊 총 ${logs.total || 0}건의 로그 분석 완료`,
                        blocks: [
                            {
                                type: "header",
                                text: {
                                    type: "plain_text",
                                    text: "📈 YAGO SPORTS 주간 리포트"
                                }
                            },
                            {
                                type: "section",
                                text: {
                                    type: "mrkdwn",
                                    text: `📅 *작성일:* ${new Date().toLocaleDateString("ko-KR")}\n📊 *총 로그:* ${logs.total || 0}건\n🌍 *지역 샘플:* ${logs.geoSample?.length || 0}개`
                                }
                            },
                            {
                                type: "section",
                                text: {
                                    type: "mrkdwn",
                                    text: `*주요 요약:*\n${report.summary || "데이터 분석 중..."}`
                                }
                            }
                        ]
                    })
                });
                console.log("✅ Slack 전송 완료");
            } catch (slackError) {
                console.warn("⚠️ Slack 전송 실패:", slackError);
            }
        }

        // Uint8Array를 Buffer로 변환하여 Response 생성
        return new Response(Buffer.from(pdfBytes), {
            headers: {
                "Content-Type": "application/pdf",
                "Content-Disposition": `attachment; filename=YAGO_VIBE_Weekly_Report_${new Date().toISOString().split('T')[0]}.pdf`,
                "Access-Control-Allow-Origin": "*",
                "Access-Control-Allow-Methods": "POST, OPTIONS",
                "Access-Control-Allow-Headers": "Content-Type"
            },
        });

    } catch (err) {
        console.error("❌ 주간 리포트 생성 오류:", err);

        // 오류 시 기본 PDF 생성
        try {
            const pdf = await PDFDocument.create();
            const page = pdf.addPage([595.28, 841.89]);
            const font = await pdf.embedFont(StandardFonts.Helvetica);

            page.drawText("❌ YAGO SPORTS 주간 리포트 생성 오류", {
                x: 50,
                y: 750,
                size: 16,
                font,
                color: rgb(0.8, 0.2, 0.2)
            });

            page.drawText(`오류 발생: ${err instanceof Error ? err.message : 'Unknown error'}`, {
                x: 50,
                y: 700,
                size: 12,
                font,
                color: rgb(0.4, 0.4, 0.4)
            });

            page.drawText(`발생 시간: ${new Date().toLocaleString("ko-KR")}`, {
                x: 50,
                y: 650,
                size: 10,
                font,
                color: rgb(0.4, 0.4, 0.4)
            });

            const pdfBytes = await pdf.save();

            return new Response(Buffer.from(pdfBytes), {
                status: 500,
                headers: {
                    "Content-Type": "application/pdf",
                    "Content-Disposition": `attachment; filename=YAGO_VIBE_Error_Report_${new Date().toISOString().split('T')[0]}.pdf`
                }
            });
        } catch (pdfError) {
            console.error("❌ PDF 생성도 실패:", pdfError);
            return new Response("Internal Server Error", { status: 500 });
        }
    }
};

// CORS preflight 요청 처리
export const OPTIONS = async () => {
    return new Response(null, {
        status: 200,
        headers: {
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Methods": "POST, OPTIONS",
            "Access-Control-Allow-Headers": "Content-Type"
        }
    });
};
