/** 운영 고지·동의 UI — 사용자 노출 문구 (개발 용어 금지) */

export const ACADEMY_UPLOAD_CONSENT = {
  uploadRight:
    "본인은 해당 영상의 업로드 권한을 보유하고 있습니다.",
  aiAnalysis:
    "업로드한 영상이 AI 분석 및 성장 리포트 생성에 사용되는 것에 동의합니다.",
  guardianMinor:
    "미성년자 선수의 경우 법정대리인(학부모)의 동의를 받았습니다.",
} as const;

export const SIGNUP_GUARDIAN_CONSENT = {
  isGuardianLabel: "학부모·법정대리인으로 가입합니다",
  legalGuardian:
    "만 14세 미만 선수의 경우 법정대리인입니다.",
  aiDataProcessing:
    "자녀의 영상 및 훈련 데이터를 AI 분석 목적으로 처리하는 것에 동의합니다.",
} as const;

export const GROWTH_REPORT_PDF_DISCLAIMER = {
  generatedFrom:
    "본 리포트는 업로드된 영상과 AI 분석 결과를 기반으로 생성되었습니다.",
  referenceOnly:
    "본 리포트는 참고용 자료이며 선수 선발·평가의 유일한 기준으로 사용될 수 없습니다.",
  generatedBy: "Generated by YAGO AI Growth",
} as const;
