import React from 'react';

interface YagoLayoutProps {
    children: React.ReactNode;
    title?: string;
    showFooter?: boolean;
}

export default function YagoLayout({
    children,
    title = "YAGO SPORTS Dashboard",
    showFooter = true
}: YagoLayoutProps) {
    return (
        <div className="min-h-screen bg-yago-soft flex flex-col">
            {/* 🎨 브랜드 헤더 */}
            <header className="bg-yago-gradient shadow-lg text-white">
                <div className="container mx-auto px-6 py-4">
                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3">
                            {/* 로고 영역 */}
                            <div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center">
                                <span className="text-2xl font-bold text-white">Y</span>
                            </div>
                            <div>
                                <h1 className="text-2xl font-display font-bold tracking-wide">
                                    {title}
                                </h1>
                                <p className="text-sm opacity-90">
                                    AI-Powered Voice Command Analytics
                                </p>
                            </div>
                        </div>

                        {/* 상태 표시 */}
                        <div className="flex items-center gap-2">
                            <div className="w-3 h-3 bg-green-400 rounded-full animate-yago-pulse"></div>
                            <span className="text-sm font-medium">System Online</span>
                        </div>
                    </div>
                </div>
            </header>

            {/* 📊 메인 컨텐츠 */}
            <main className="flex-1 container mx-auto px-6 py-8">
                {children}
            </main>

            {/* 📎 브랜드 푸터 */}
            {showFooter && (
                <footer className="bg-yago-purple text-white text-center py-3">
                    <div className="container mx-auto px-6">
                        <p className="text-sm font-medium">
                            Generated by YAGO SPORTS AI System •
                            <span className="ml-2 opacity-75">
                                {new Date().toLocaleDateString('ko-KR')}
                            </span>
                        </p>
                    </div>
                </footer>
            )}
        </div>
    );
}
